---
- name: Install commonly-used tools
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - jq
    - curl
    - unzip
    - net-tools
    - vim
    - s3cmd
    - memstat
    - sysstat
    - python-pip
    - ruby-full
